# Generated by Django 5.2.9 on 2025-12-17 20:42

from django.db import migrations, models


def convert_empty_to_null(apps, schema_editor):
    """Convert empty reference_number strings to NULL."""
    Payment = apps.get_model("django_athm", "Payment")
    Payment.objects.filter(reference_number="").update(reference_number=None)


def convert_null_to_empty(apps, schema_editor):
    """Reverse: convert NULL reference_number to empty string."""
    Payment = apps.get_model("django_athm", "Payment")
    Payment.objects.filter(reference_number__isnull=True).update(reference_number="")


class Migration(migrations.Migration):

    dependencies = [
        ("django_athm", "0001_initial"),
    ]

    operations = [
        # First allow NULL values
        migrations.AlterField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="ATH Móvil reference number for completed transactions",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        # Then convert existing empty strings to NULL
        migrations.RunPython(convert_empty_to_null, convert_null_to_empty),
    ]
