# Generated by Django 5.2.9 on 2025-12-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_athm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookevent",
            old_name="transaction",
            new_name="payment",
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated payment if found/created",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="django_athm.payment",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="refund",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated refund for refund webhooks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="django_athm.refund",
            ),
        ),
    ]
