# Generated by Django 4.2.26 on 2025-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0003_athm_client_alter_athm_item_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athm_item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="athm_item",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
