# Generated by Django 4.2.26 on 2025-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0003_athm_client_alter_athm_item_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athm_transaction",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Customer name from ATH Móvil account",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Customer phone from ATH Móvil account",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="ecommerce_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ATH Móvil eCommerce transaction ID",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="ecommerce_status",
            field=models.CharField(
                blank=True,
                help_text="Status from ATH Móvil API",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="net_amount",
            field=models.FloatField(
                blank=True, help_text="Net amount after fees", null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirm", "Confirm"),
                    ("completed", "Completed"),
                    ("cancel", "Cancel"),
                    ("refunded", "Refunded"),
                    ("processing", "Processing (Legacy)"),
                ],
                default="processing",
                max_length=16,
            ),
        ),
    ]
