# Generated by Django 4.2.26 on 2025-11-25
# Squashed: 0004_add_athm_v1_fields through 0008_change_client_on_delete_to_set_null

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0003_athm_client_alter_athm_item_options_and_more"),
    ]

    operations = [
        # Add v4 API fields to transaction
        migrations.AddField(
            model_name="athm_transaction",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Customer name from ATH Móvil account",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Customer phone from ATH Móvil account",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="ecommerce_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ATH Móvil eCommerce transaction ID",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="ecommerce_status",
            field=models.CharField(
                blank=True,
                help_text="Status from ATH Móvil API",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="athm_transaction",
            name="net_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net amount after fees",
                max_digits=10,
                null=True,
            ),
        ),
        # Update status choices (remove legacy processing status)
        migrations.AlterField(
            model_name="athm_transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirm", "Confirm"),
                    ("completed", "Completed"),
                    ("cancel", "Cancel"),
                    ("refunded", "Refunded"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        # Fix metadata length limits
        migrations.AlterField(
            model_name="athm_item",
            name="metadata",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="metadata_1",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="metadata_2",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        # Add indexes and ordering
        migrations.AlterModelOptions(
            name="athm_transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "ATH Móvil Transaction",
                "verbose_name_plural": "ATH Móvil Transactions",
            },
        ),
        migrations.AddIndex(
            model_name="athm_transaction",
            index=models.Index(fields=["-date"], name="django_athm_date_594b0e_idx"),
        ),
        migrations.AddIndex(
            model_name="athm_transaction",
            index=models.Index(
                fields=["status", "-date"], name="django_athm_status_3e95ae_idx"
            ),
        ),
        # Convert float fields to decimal
        migrations.AlterField(
            model_name="athm_item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="athm_item",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        # Change client FK to SET_NULL to preserve transaction history
        migrations.AlterField(
            model_name="athm_transaction",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                related_query_name="transaction",
                to="django_athm.athm_client",
            ),
        ),
    ]
