# Generated by Django 4.2.26 on 2025-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0004_add_athm_v1_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athm_item",
            name="metadata",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="metadata_1",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="metadata_2",
            field=models.CharField(
                blank=True, help_text="Max 40 characters", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirm", "Confirm"),
                    ("completed", "Completed"),
                    ("cancel", "Cancel"),
                    ("refunded", "Refunded"),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
