# Generated by Django 5.2.9 on 2025-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_athm", "0004_webhook_backend_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athm_transaction",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="athm_webhookevent",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
