# Generated by Django 4.2.26 on 2025-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0005_fix_metadata_length_limits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athm_transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "ATH Móvil Transaction",
                "verbose_name_plural": "ATH Móvil Transactions",
            },
        ),
        migrations.AddIndex(
            model_name="athm_transaction",
            index=models.Index(fields=["-date"], name="django_athm_date_594b0e_idx"),
        ),
        migrations.AddIndex(
            model_name="athm_transaction",
            index=models.Index(
                fields=["status", "-date"], name="django_athm_status_3e95ae_idx"
            ),
        ),
    ]
