# Generated by Django 4.2.26 on 2025-11-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_athm", "0006_add_transaction_indexes_and_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athm_item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="athm_item",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="net_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net amount after fees",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="athm_transaction",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
